### ISSUE TITLE
Outermost regions map

### ISSUE THREAD

**Issue by Dgojsic** [ec-doris/kohesio-frontend#1064]
When selecting outermost regions, projects will only load after zooming/dragging

**Comment by raphdom** [comment]
Now it is working, only "Azores" that the bbox is not correct, but this is coming from the API, even in the filters the bbox is not working properly. Can you take a look @DiaZork?

**Comment by DiaZork** [comment]
I fixed the fact that no point was appearing so now it is working but because of the specific geography of this islands it's not perfect as there is only one nuts in this place

**Comment by raphdom** [comment]
Done, deployed on ACC, now is ready to test, please @Dgojsic

**Comment by Dgojsic** [comment]
![Image](https://github.com/user-attachments/assets/06b1c2c7-6925-483e-8901-10fcfe779451)

Issue persisting with orange layers adding on top of each other with each drag
