### ISSUE TITLE
Vertical scrollbar and bottom cut in filters - map tab

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#602]
https://kohesio.acceptance.ec.europa.eu/projects?keywords=migrant&sort=Total-Budget-(descending)&tab=map

![filters_vertical_scroll](https://user-images.githubusercontent.com/942488/158153240-c0dad4be-c739-4cde-9e66-1e4df636e76a.png)

**Comment by madewild** [comment]
also on audiovisual tab: https://kohesio.acceptance.ec.europa.eu/projects?keywords=migrant&sort=Total-Budget-(descending)&tab=audiovisual

**Comment by raphdom** [comment]
fixed, you can test it on dev and test environments...

**Comment by madewild** [comment]
Sorry I still have the issue on https://kohesio.test.ec.europa.eu/en/projects?keywords=ai&sort=Total-Budget-(descending)&tab=map with advanced filters open...

**Comment by raphdom** [comment]
@madewild  now should be fine...
