### ISSUE TITLE
Unable to move map after focus

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-frontend#633]
- Go to https://kohesio.ec.europa.eu/
- Hover over Ukraine (for instance): the cursor is a hand and you can move the map around
- Hover over Poland: the cursor becomes a pointer
- Hover over Ukraine again: now the cursor is an arrow and you cannot move the map anymore!

**Comment by madewild** [comment]
If the cursor leaves the map and comes again, then it's fine.

**Comment by raphdom** [comment]
fixed on dev, can you check?

**Comment by madewild** [comment]
@raphdom we noticed that this bug is still happening but with project blue circles:

- go to home page
- click projects near me
- hover over a project blue circle
- put your mouse over the map again: there is no hand and you cannot drag it

could you fix this when you have time (along with #686 ) and do a fast release to prod? thx

**Comment by raphdom** [comment]
ok, now is fixed on PROD

**Comment by raphdom** [comment]
@madewild can you check this, I think we can close it
